	<option value="">Silahkan Pilih</option>
	<option value="BCA">BCA</option>
	<option value="BNI">BNI 46</option>
	<option value="BRI">BRI</option>
	<option value="BRI Syariah">BRI Syariah</option>
	<option value="CIMB Niaga">CIMB Niaga</option>
	<option value="DANAMON">DANAMON</option>
	<option value="Permata">Permata</option>
	<option value="Mandiri">Mandiri</option>
	<option value="Mandiri Syariah">Mandiri Syariah</option>
	<option value="BII">BII Maybank</option>
	<option value="OCBC NISP">OCBC NISP</option>
	<option value="BTN">BTN</option>
	<option value="Citibank">Citibank</option>
	<option value="Muamalat">Muamalat</option>
	<option value="Mega">Mega</option>
	<option value="Bukopin">Bukopin</option>
	<option value="HSBC">HSBC</option>
	<option value="ANZ-Panin">ANZ-Panin </option>
	<option value="Standard Chartered">Standard Chartered </option>
	<option value="UOB Buana">UOB Buana</option>
	<option value="DBS">DBS</option>
	<option value="Sinarmas">Sinarmas</option>
	<option value="DKI">DKI</option>
	<option value="Commonwealth">Commonwealth</option>
	<option value="Artha Graha">Artha Graha</option>
	<option value="JTrust">JTrust</option>
	<option value="Mayapada Internasional">Mayapada Internasional</option>
	<option value="Nagari">Nagari</option>
	<option value="BNP">BNP</option>
	<option value="Mestika">Mestika</option>
	<option value="Woori Saudara">Woori Saudara</option>
	<option value="Jabar Banten Syariah">Jabar Banten Syariah</option>
	<option value="ICB Bumiputera">ICB Bumiputera</option>
	<option value="Nobu">Nobu</option>
	<option value="Ekonomi">Ekonomi</option>
	<option value="Victoria">Victoria</option>
	<option value="Syariah Mega Indonesia"> Syariah Mega Indonesia</option>
	<option value="BTPN">BTPN</option>

